services:

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
      - 7946
      - 9095
  
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    restart: always
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml
    command: ["-config.file=/etc/tempo.yaml"]

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    restart: always
    ports:
      - "9090:9090"
    command: ["-config.file=/etc/mimir.yaml"]
    volumes:
      - ./config/mimir/mimir.yaml:/etc/mimir.yaml
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_FORM_LOGIN=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    depends_on:
      - loki
      - tempo
      - mimir
  
  otel:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel
    restart: always
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./config/otel/otel.yaml:/etc/otelcol/config.yaml
    depends_on:
      - loki
      - tempo
      - mimir
      - grafana

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: ["-config.file=/etc/promtail/config.yaml"]