apiVersion: 1 

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: false
    version: 1
    uid: loki

  - name: Tempo
    type: tempo
    access: proxy
    url: http://loki:3200
    isDefault: true
    editable: false
    version: 1
    uid: tempo

  - name: Mimir
    type: prometheus
    access: proxy
    url: http://mimir:9090/prometheus
    basicAuth: false
    isDefault: false
    editable: false
    version: 1
    uid: mimir